### ISSUE TITLE
Super Mario 64 PAL

### ISSUE THREAD

**Issue by shadow2560** [FIX94/GetExtTypePatcher#1]
Helo,

I encounter a stange thing with the wad of Super Mario 64 PAL. When I extract it, there is no a 00000001.app file. Here is the list of the files in the wad:
- 0000000a.app
00000002.app
- 00000003.app
- 00000004.app
- 00000006.app
- 00000008.app
- 00000009.app
- 000100014e414150.cert
- 000100014e414150.footer
- 000100014e414150.tik
- 000100014e414150.tmd

If I want the patch to be applied, I must use GetExtTypePatcher on the 00000008.app file. If I do that, the patch is applied like it should.

Because of this strange structure of files, I don't want to try to install it on my Wii U v-wii nand cause I don't want to brick it. The wad launch properly on Dolphin emulator.

I realy want to have your advice on this.

**Comment by FIX94** [comment]
some wad files have a strange content layout because of possibly recieved updates or weirdly packed wads, it should not matter though and should be safe to install.

**Comment by shadow2560** [comment]
OK, thanks for your answer.
